version: "3.9"

services:
  db:
    image: postgres:15
    container_name: taskflow_db
    restart: always
    enviroments:
      POSTGRES_DB: taskflow
      POSTGRES_USER: taskflow_user
      POSTGRES_PASSWORD: 12345678
  ports: 
    - "5432:5432"
  volumes: 
    - postgres_data:/var/lib/postgresql/data

  backend:
    build: .
    container_name: taskflow_backend
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - .:/app 
    ports: 
      - "8000:8000"
    depends_on:
      - db 
    environment:
      DEBUG: "True" 
      DATABASE_NAME: taskflow
      DATABASE_USER: postgres 
      DATABASE_PASSWORD: 12345678
      DATABASE_HOST: db 
      DABATASE_PORT: 5432

  volumes:
    postgres_data:
