# Generated by Django 6.0.1 on 2026-03-10 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='refreshtoken',
            name='revoked',
            field=models.BooleanField(default=False),
        ),
    ]
